### ISSUE TITLE
楼主我为什么运行报错

### ISSUE THREAD

**Issue by dongpeng66** [yanhe0317/DingDong#1]
Traceback (most recent call last):
  File "/Users/dp/Downloads/DingDong-master/main.py", line 4, in <module>
    import pyautogui
  File "/Users/dp/Library/Python/2.7/lib/python/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/Users/dp/Library/Python/2.7/lib/python/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/Users/dp/Library/Python/2.7/lib/python/site-packages/rubicon/objc/__init__.py", line 3, in <module>
    from .runtime import (  # noqa: F401
  File "/Users/dp/Library/Python/2.7/lib/python/site-packages/rubicon/objc/runtime.py", line 785
    self.restype, *self.argtypes = ctypes_for_method_encoding(self.encoding)
                  ^
SyntaxError: invalid syntax

**Comment by Arcxia** [comment]
Python版本好像低了，你用的是Mac吧，我这边Windows跑的，可能环境也有点区别。

**Comment by jackiehj** [comment]
> 

还能抢菜吗？

**Comment by Arcxia** [comment]
> > 
> 
> 还能抢菜吗？

可以，但要自己改下。
